# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aef3e108bcf83059467b2788371b0960"
name = "Test-001"
handle = "test-16169"
application_url = "https://coleman-trend-gay-volume.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellostorexyz.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://coleman-trend-gay-volume.trycloudflare.com/auth/callback",
  "https://coleman-trend-gay-volume.trycloudflare.com/auth/shopify/callback",
  "https://coleman-trend-gay-volume.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
