# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ca8c6e344e7e7930741d19a67c13759"
name = "App0101"
handle = "App0101"
application_url = "https://reasoning-candy-inputs-washington.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellostorexyz.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reasoning-candy-inputs-washington.trycloudflare.com/auth/callback",
  "https://reasoning-candy-inputs-washington.trycloudflare.com/auth/shopify/callback",
  "https://reasoning-candy-inputs-washington.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
